https://www.youtube.com/watch?v=vjMeYeGe7F4

## 1. Numpy

In [3]:
import numpy as np

In [8]:
data = [[1, 2, 3.0], [4, 5, 6], [7, 8 ,9]]

a = np.array(data)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [9]:
a.dtype

dtype('float64')

In [10]:
data = [[1, 2, 3], [4, 5, 6], [7, 8 ,9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
type(a)

numpy.ndarray

In [13]:
dir(a) 

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [14]:
a.dtype # 이렇게 사용하기

dtype('int32')

In [15]:
a = a.astype(np.float32)  # in32 -> float32
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [17]:
a[0][1]

2.0

In [18]:
a[0]

array([1., 2., 3.], dtype=float32)

In [19]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [20]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(1, 13).reshape(3, 3) # 갯수 맞춰야함

ValueError: cannot reshape array of size 12 into shape (3,3)

In [25]:
np.arange(1, 13).reshape(3, 2, 2) 

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [26]:
np.nan * 10

nan

In [27]:
np.nan +10

nan

In [29]:
a[0][1] =np.nan
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [33]:
a = np.arange(1, 10).reshape(3, 3)
a.dtype

dtype('int32')

In [35]:
a[0][1] = np.nan  # integer에서는 nan을 사용할 수 없다 (float형에서 사용가능)

ValueError: cannot convert float NaN to integer

In [36]:
a = np.linspace(1, 10, 10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
a = np.linspace(1, 10, 20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 연산

In [40]:
data = np.arange(1, 10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [42]:
[1, 2, 3,] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [43]:
data -data

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
data * data # 내적값이 아님

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [45]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
#행렬의 곱(내적)
np.dot(data, data) 

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [47]:
data@data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### 차원

In [50]:
# 0 차원 : 스칼라
a = np.array(1)
a

array(1)

In [54]:
a.shape # 0차원이라 shape이 없다고 나옴

()

In [55]:
a.ndim #차원

0

In [57]:
# 1차원 : 벡터 
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [59]:
a.shape

(5,)

In [60]:
a.ndim

1

In [61]:
# 2차원 : 매트릭스
a = np.array([[1]])
a

array([[1]])

In [62]:
a.shape

(1, 1)

In [63]:
a.ndim

2

In [66]:
# 3차원 : 3차원 이상의 다차원의 행렬을 Tensor
a = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [67]:
a.shape

(2, 3, 2)

In [68]:
a.ndim

3

### matrix의 유형

In [71]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [78]:
b = np.arange(12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
b =np.ones(12)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
b = np.zeros(12).reshape(2, 3, 2)
b

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [83]:
f = np.empty([2, 3]) 
f

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
g = np.full((3, 4), 1000)

In [85]:
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [87]:
h = np.linspace(2, 10, 6) #2~10를 6개로 균등하게

h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

### 집계 함수

In [90]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [91]:
a[0][0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [92]:
a[0, 1] = 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [93]:
np.mean(a)

114.4

In [94]:
np.median(a)

6.5

In [95]:
np.std(a) #표준편차

296.5485457728633

In [97]:
np.var(a) #분산

87941.04

In [98]:
np.sum(a, axis = 0)

array([ 105, 1006,    9,   11,   13])

In [99]:
np.sum(a, axis = 1)

array([1109,   35])

## Pandas

In [103]:
import pandas as pd
import numpy as np

In [127]:
data = np.arange(0, 50, 10)
data

array([ 0, 10, 20, 30, 40])

In [128]:
a = pd.Series(data, index = ['a', 'b', 'c', 'd', 'e'])
a

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [129]:
b = pd.Series(data)
b

0     0
1    10
2    20
3    30
4    40
dtype: int32

In [130]:
a['b']

10

In [131]:
a.loc['b']

10

In [132]:
a.iloc[1]

10

### 산술연산

In [133]:
a

a     0
b    10
c    20
d    30
e    40
dtype: int32

In [155]:
#a +10
#a -10
#a *10
#a **2
#a / 5
a // 5
#a % 3

a    0
b    2
c    4
d    6
e    8
dtype: int32

In [156]:
a > 15

a    False
b    False
c     True
d     True
e     True
dtype: bool

In [157]:
a[a>15]

c    20
d    30
e    40
dtype: int32

### 집계함수

In [159]:
a.add(100)

a    100
b    110
c    120
d    130
e    140
dtype: int32

In [160]:
a.sub(100)

a   -100
b    -90
c    -80
d    -70
e    -60
dtype: int32

In [161]:
a.mul(100)

a       0
b    1000
c    2000
d    3000
e    4000
dtype: int32

In [162]:
a.div(100)

a    0.0
b    0.1
c    0.2
d    0.3
e    0.4
dtype: float64

In [163]:
a.mod(3)

a    0
b    1
c    2
d    0
e    1
dtype: int32

In [164]:
a.min()

0

In [165]:
a.max()

40

In [166]:
a.sum()

100

In [167]:
a.mean()

20.0

In [168]:
a.std()

15.811388300841896

In [169]:
a.var()

250.0

### DataFrame

In [172]:
rawData = np.random.randint(50, 100, size = (4, 3))
rawData

array([[81, 58, 91],
       [63, 56, 67],
       [79, 57, 76],
       [80, 99, 86]])

In [195]:
df = pd.DataFrame(rawData, 
                  index= ['1반', '2반', '1반', '2반'],
                  columns = ['국', '영', '수'])
df

국   영   수
1반  81  58  91
2반  63  56  67
1반  79  57  76
2반  80  99  86

In [175]:
df['국']

1반    81
2반    63
1반    79
2반    80
Name: 국, dtype: int32

In [177]:
# df[0] # Error

In [178]:
df

국   영   수
1반  81  58  91
2반  63  56  67
1반  79  57  76
2반  80  99  86

In [179]:
df['평균'] = round((df['국'] + df['영'] + df['수'])/3, 2) #나눈값을 소숫점 2자리까지
df

국   영   수     평균
1반  81  58  91  76.67
2반  63  56  67  62.00
1반  79  57  76  70.67
2반  80  99  86  88.33

In [180]:
df['na'] = np.nan
df

국   영   수     평균  na
1반  81  58  91  76.67 NaN
2반  63  56  67  62.00 NaN
1반  79  57  76  70.67 NaN
2반  80  99  86  88.33 NaN

In [181]:
del df['na']
df

국   영   수     평균
1반  81  58  91  76.67
2반  63  56  67  62.00
1반  79  57  76  70.67
2반  80  99  86  88.33

In [182]:
df[df.평균>75]

국   영   수     평균
1반  81  58  91  76.67
2반  80  99  86  88.33

In [183]:
df = df.drop(['평균'], axis = 'columns')
df

국   영   수
1반  81  58  91
2반  63  56  67
1반  79  57  76
2반  80  99  86

### 결측값 처리

In [198]:
df = df.astype('float64')
df

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
1반  79.0  57.0  76.0
2반  80.0  99.0  86.0

In [187]:
df['수'][2] = np.nan
df

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
1반  79.0  57.0   NaN
2반  80.0  99.0  86.0

In [188]:
df.dropna(axis = 0) 

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
2반  80.0  99.0  86.0

In [192]:
df # inplace =False가 default

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
2반  80.0  99.0  86.0

In [193]:
df.dropna(axis = 0, inplace = True) # df 바뀜
df

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
2반  80.0  99.0  86.0

In [199]:
df

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
1반  79.0  57.0  76.0
2반  80.0  99.0  86.0

In [200]:
df['수'][2] = np.nan #float으로 해야 np.nan 실행됨
df

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
1반  79.0  57.0   NaN
2반  80.0  99.0  86.0

In [201]:
df. dropna(axis =1)

국     영
1반  81.0  58.0
2반  63.0  56.0
1반  79.0  57.0
2반  80.0  99.0

In [202]:
df

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
1반  79.0  57.0   NaN
2반  80.0  99.0  86.0

In [203]:
df.fillna('hello')

국     영      수
1반  81.0  58.0   91.0
2반  63.0  56.0   67.0
1반  79.0  57.0  hello
2반  80.0  99.0   86.0

In [204]:
df.fillna(df.mean())

국     영          수
1반  81.0  58.0  91.000000
2반  63.0  56.0  67.000000
1반  79.0  57.0  81.333333
2반  80.0  99.0  86.000000

In [205]:
df

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
1반  79.0  57.0   NaN
2반  80.0  99.0  86.0

### MultiIndex

In [208]:
df

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
1반  79.0  57.0   NaN
2반  80.0  99.0  86.0

In [209]:
df.T # columns와 row 바꿈

1반    2반    1반    2반
국  81.0  63.0  79.0  80.0
영  58.0  56.0  57.0  99.0
수  91.0  67.0   NaN  86.0

In [210]:
df

국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0
1반  79.0  57.0   NaN
2반  80.0  99.0  86.0

In [212]:
df.index = [['1학년', '1학년', '2학년', '2학년'], ['1반', '2반', '1반', '2반']]
df

국     영     수
1학년 1반  81.0  58.0  91.0
    2반  63.0  56.0  67.0
2학년 1반  79.0  57.0   NaN
    2반  80.0  99.0  86.0

In [213]:
df.columns = [['언어', '언어', '수리'], ['국', '영', '수']]
df

언어          수리
           국     영     수
1학년 1반  81.0  58.0  91.0
    2반  63.0  56.0  67.0
2학년 1반  79.0  57.0   NaN
    2반  80.0  99.0  86.0

In [214]:
df['언어']['국']

1학년  1반    81.0
     2반    63.0
2학년  1반    79.0
     2반    80.0
Name: 국, dtype: float64

In [215]:
df.iloc[0]

언어  국    81.0
    영    58.0
수리  수    91.0
Name: (1학년, 1반), dtype: float64

In [216]:
df.loc['1학년']

언어          수리
       국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0

In [218]:
df.loc['1학년']

언어          수리
       국     영     수
1반  81.0  58.0  91.0
2반  63.0  56.0  67.0

In [217]:
df.loc['1학년'].loc['1반']

언어  국    81.0
    영    58.0
수리  수    91.0
Name: 1반, dtype: float64

### 데이터 사전 분석

In [221]:
df

언어          수리
           국     영     수
1학년 1반  81.0  58.0  91.0
    2반  63.0  56.0  67.0
2학년 1반  79.0  57.0   NaN
    2반  80.0  99.0  86.0

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('1학년', '1반') to ('2학년', '2반')
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   (언어, 국)  4 non-null      float64
 1   (언어, 영)  4 non-null      float64
 2   (수리, 수)  3 non-null      float64
dtypes: float64(3)
memory usage: 384.0+ bytes


In [223]:
df.head()

언어          수리
           국     영     수
1학년 1반  81.0  58.0  91.0
    2반  63.0  56.0  67.0
2학년 1반  79.0  57.0   NaN
    2반  80.0  99.0  86.0

In [224]:
df.tail()

언어          수리
           국     영     수
1학년 1반  81.0  58.0  91.0
    2반  63.0  56.0  67.0
2학년 1반  79.0  57.0   NaN
    2반  80.0  99.0  86.0

In [225]:
df.dtypes

언어  국    float64
    영    float64
수리  수    float64
dtype: object

In [226]:
df.describe()

언어                    수리
               국          영          수
count   4.000000   4.000000   3.000000
mean   75.750000  67.500000  81.333333
std     8.539126  21.015867  12.662280
min    63.000000  56.000000  67.000000
25%    75.000000  56.750000  76.500000
50%    79.500000  57.500000  86.000000
75%    80.250000  68.250000  88.500000
max    81.000000  99.000000  91.000000

In [227]:
df.isnull()

언어            수리
            국      영      수
1학년 1반  False  False  False
    2반  False  False  False
2학년 1반  False  False   True
    2반  False  False  False

In [228]:
df.isnull().sum()

언어  국    0
    영    0
수리  수    1
dtype: int64

### 값의 연결

In [231]:
a = pd.DataFrame(np.arange(1, 10).reshape(3, 3))
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [232]:
b = pd.Series(np.arange(10, 40, 10))
b

0    10
1    20
2    30
dtype: int32

In [233]:
pd.concat([a, b], axis=1)

0  1  2   0
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [234]:
pd.concat([a, b], axis=1, ignore_index = True)

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [235]:
a.append(b, ignore_index = True)

C:\Users\Public\Documents\ESTsoft\CreatorTemp/ipykernel_17188/1061858700.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  a.append(b, ignore_index = True)


0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30